from enum import Enum


class TradeType(str, Enum):
    BUY = 'BUY'
    SELL = 'SELL'


class P2PCryptoAssetType(str, Enum):
    USDT = 'USDT'
    BTC = 'BTC'
    BUSD = 'BUSD'
    BNB = 'BNB'
    ETH = 'ETH'


class P2PFiatCurrencyType(str, Enum):
    """Actual list is on https://p2p.binance.com/bapi/fiat/v1/public/fiatpayment/menu/currency"""
    CHF = 'CHF'
    MXN = 'MXN'
    VES = 'VES'
    CLP = 'CLP'
    UGX = 'UGX'
    ZAR = 'ZAR'
    TND = 'TND'
    TZS = 'TZS'
    VND = 'VND'
    AUD = 'AUD'
    ILS = 'ILS'
    GHS = 'GHS'
    BOB = 'BOB'
    IDR = 'IDR'
    SDG = 'SDG'
    AMD = 'AMD'
    TRY = 'TRY'
    LBP = 'LBP'
    TJS = 'TJS'
    AED = 'AED'
    TWD = 'TWD'
    EUR = 'EUR'
    DOP = 'DOP'
    DKK = 'DKK'
    CAD = 'CAD'
    BGN = 'BGN'
    MMK = 'MMK'
    XOF = 'XOF'
    GEL = 'GEL'
    RON = 'RON'
    UYU = 'UYU'
    MAD = 'MAD'
    LKR = 'LKR'
    NGN = 'NGN'
    CZK = 'CZK'
    AZN = 'AZN'
    CRC = 'CRC'
    OMR = 'OMR'
    PKR = 'PKR'
    SEK = 'SEK'
    KES = 'KES'
    UAH = 'UAH'
    BHD = 'BHD'
    ARS = 'ARS'
    QAR = 'QAR'
    KZT = 'KZT'
    SAR = 'SAR'
    INR = 'INR'
    CNY = 'CNY'
    THB = 'THB'
    UZS = 'UZS'
    JPY = 'JPY'
    MNT = 'MNT'
    PLN = 'PLN'
    GBP = 'GBP'
    BYN = 'BYN'
    HUF = 'HUF'
    PHP = 'PHP'
    KWD = 'KWD'
    RUB = 'RUB'
    PYG = 'PYG'
    ISK = 'ISK'
    COP = 'COP'
    USD = 'USD'
    EGP = 'EGP'
    DZD = 'DZD'
    PAB = 'PAB'
    KGS = 'KGS'
    PEN = 'PEN'
    NZD = 'NZD'
    XAF = 'XAF'
    BRL = 'BRL'

